#server:
#  port: 8081
#
#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/msfacturaciongestionclientes?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  application:
    name: ms-facturacion-gestion-clientes

  config:
    import: optional:configserver:http://localhost:9090