server:
  port: 9090

spring:
  application:
    name: ms-server-configuracion

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/Galaxy/Proyecto/ms-server-config-data
