server:
  port: 8083

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/msfacturaciongestionfacturas?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true