server:
  port: 9092

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#        - id: ms-facturacion-gestion-clientes
#          uri: lb://MS-FACTURACION-GESTION-CLIENTES
#          predicates:
#          - Path=/ms-facturacion-gestion-clientes/**
#          filters:
#          - RewritePath=/ms-facturacion-gestion-clientes/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always